apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels: 
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 084375555299.dkr.ecr.ap-south-1.amazonaws.com/hungnv-ecr-repo:latest
        ports:
        - containerPort: 5000
        env:
        # - name: DB_HOST
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: DB_HOST
        # - name: DB_NAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: DB_NAME
        # - name: DB_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: DB_USER
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-secrets
        #       key: DB_PASSWORD
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: AWS_REGION
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer